name: Build and Release

on:
  release:
    types: [created]

jobs:
  build-and-release:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v4.2.0
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Electron Builder
        run: npm install -g electron-builder

      - name: Generate self-signed certificate
        id: generate_cert
        run: |
          $cert_password = "$(New-Guid)"
          echo "CERTIFICATE_PASSWORD=$cert_password" >> $env:GITHUB_ENV

          # Generate self-signed certificate
          $cert = New-SelfSignedCertificate -Subject "CN=Green Meteor, O=Green Meteor, L=YourCity, S=YourState, C=YourCountry" -Type CodeSigningCert -CertStoreLocation Cert:\CurrentUser\My

          # Export to PFX
          $pwd = ConvertTo-SecureString -String $cert_password -Force -AsPlainText
          Export-PfxCertificate -Cert "Cert:\CurrentUser\My\$($cert.Thumbprint)" -FilePath cert.pfx -Password $pwd
        shell: pwsh

      - name: Build application
        env:
          CERTIFICATE_PASSWORD: ${{ env.CERTIFICATE_PASSWORD }}
        run: |
          npm run build
          electron-builder --win --publish never --config.win.signtoolOptions.certificateFile="cert.pfx" --config.win.signtoolOptions.certificatePassword="$CERTIFICATE_PASSWORD"

      - name: Get release info (GitHub API)
        id: get_release
        uses: actions/github-script@v7.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const release = await github.rest.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: context.payload.release.tag_name
            });
            return release.data.id;

      - name: Upload release assets for Windows
        uses: actions/github-script@v7.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const path = require('path');
            const distPath = path.join(process.cwd(), 'dist');

            const uploadAsset = async (file) => {
              const filePath = path.join(distPath, file);
              const fileStats = fs.statSync(filePath);
              const fileStream = fs.createReadStream(filePath);

              await github.rest.repos.uploadReleaseAsset({
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: ${{ steps.get_release.outputs.result }},
                name: file,
                data: fileStream,
                headers: {
                  'content-type': 'application/octet-stream',
                  'content-length': fileStats.size
                }
              });
            };

            // Upload exe and msi files
            const files = fs.readdirSync(distPath);
            for (const file of files) {
              if (file.endsWith('.exe') || file.endsWith('.msi')) {
                await uploadAsset(file);
              }
            }
